baseURL = "https://abicas.github.io/SapOnMicrosoftDemos/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "SAP on Azure - Tutorials and Guides"
theme = "hugo-theme-relearn"
themesdir = "themes"
#metaDataFormat = "yaml"
canonifyURLs = true

publishDir = "docs"
defaultContentLanguageInSubdir= true


[params]
#  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "SAP on Microsoft - Tutorials"
  author = "Alexandre Bicas"
  showVisitedLinks = true
  alwaysopen = false
  collapsibleMenu = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "SAP on Microsoft - Tutorials"
weight = 1
languageName = "English"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/abicas/SapOnMicrosoftDemos"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-youtube' ></i> Youtube Playlist"
url = "https://www.youtube.com/playlist?list=PLkP2IANHFwhaEowIbQ-a51_E5Sqb-xrz-"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20





